### ISSUE TITLE
Task 2: Antigen-binding CDR-H3 Design

### ISSUE THREAD

**Issue by huachui** [KyGao/ABGNN#1]
Hi, thanks for your work!

Could you please tell me how to generate 3D structure after finishing "bash finetune-exp2.sh", just like the case studies of Task 2 in the article. I'd appreciate it if you could answer!

**Comment by KyGao** [comment]
Hi, we use biotite to store the antigen, predicted antibody, and ground-truth antibody as three separate PDB files, and use Chimera for visualizing these saved PDB files. The save structure steps were implemented with reference to  https://github.com/wengong-jin/abdockgen/blob/master/predict.py

**Comment by KyGao** [comment]
Hope this addresses your question.

**Comment by a30221274** [comment]
Thank you very much for your answer!

**Comment by a30221274** [comment]
Thank you very much for your answer!
