### ISSUE TITLE
Dataset processing and the performance of AbBERT pre-training model

### ISSUE THREAD

**Issue by a30221274** [KyGao/ABGNN#2]
Hi there,

First of all, I want to express my admiration for the excellent work you've done on this project. The effort and dedication are truly commendable.

I have a couple of questions regarding the data preprocessing aspect. Could you please share insights into how you processed the data from the OAS database into seq.train/valid/test.tokens and the corresponding tag.train/valid/test.tokens files?

Additionally, if I intend to evaluate the performance of Abbert using an external dataset, what would be the recommended approach?

I'm eagerly looking forward to your response and appreciate any guidance you can provide.

Thank you!

**Comment by s1234533** [comment]
+1

**Comment by KyGao** [comment]
Hi, sorry for the late reply. And thanks for expressing interest in our work.

The OAS database provides a bunch of CSV files for both paired and unpaired antibodies. Following the methodology outlined in [previous research](https://www.biorxiv.org/content/10.1101/2022.08.16.504181v1.full.pdf), we filter out invalid sequences. We then concatenate the framework regions and CDRs to form the complete heavy-chain Fv sequences of the antibodies, along with their associated tag information. Rules for this process are detailed in the following 
(snipaste from the original paper). ![Snipaste_2024-03-05_21-02-43](https://github.com/KyGao/ABGNN/assets/61086531/a583e7a2-a8b5-4079-8fed-676c7f8dcc07) 

Given the vast quantity of data (approximately billions of sequences), we employ [MMseqs2](https://github.com/soedinglab/MMseqs2) to cluster this data. We specifically utilize Linclust to accelerate the process.

Finally, we randomly sample 50 million sequences for pretraining. each data has an antibody sequence and its according tag sequence. Examples can be found in the attached `seqs.example.tokens` and `tags.example.tokens`.
[example.zip](https://github.com/KyGao/ABGNN/files/14496263/example.zip)

**Comment by KyGao** [comment]
As for the evaluation of abbert. You can refer to the `inference.py` and write your own `from_pretrained` function. As long as the `args.finetune=False`, the model is abbert

**Comment by s1234533** [comment]
Please forgive me for being a beginner. Can you provide a script for how to make sequence data into `.tokens` file

**Comment by KyGao** [comment]
Do you mean the sequence data after final sampling? The `.tokens` is a marker; sequence data are raw texts. You can simply convert the file extension from `.txt` to `.tokens`.

**Comment by a30221274** [comment]
Thank you very much for your answer, which solved my confusion.

**Comment by a30221274** [comment]
Hello, regarding the validation of the abbert model's performance, I first convert my own validation data into token format and then preprocess it.   Should I use the AntibodyRobertaModel framework, set args.finetune=False, and load the checkpoint215.pt provided by you for validation?

**Comment by KyGao** [comment]
Yes, you are right. You can refer to `inference.py` to construct your own dataset and infer.

**Comment by a30221274** [comment]
Ok, thank you again.

**Comment by KyGao** [comment]
Since all problems are solved, I'll close this issue. 
If you have any more questions, feel free to reopen or launch a new issue.
